name: "Hello world workflow"

#controls when the actions will run. Triggers the workflow on push some to master and production branches
on: 
    push:
      branches:
        - master
        - production

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
        - name: "Print hello world"
          run: echo "Hello world"

        - name: "Print curent date"
          run: date 