name: "Mjlti event pipeline / workflow"  # name of the pipeline

on: 
    push:  # Event: whenever a push is made to the repository on the master/test branch
        branches:
            - master
            - test

    pull_request: # Event: whenever a pull request is made to the repository
        branches:
            - master
        types:
            - closed

    workflow_dispatch:


jobs:
    on-push: # job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master/test push" # step 1
              run: echo "Running on master push"

    on-pull-request: # job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
        - name: "Running on master pull request" # step 1
          run: echo "Running on master pull request"

    on-pull-request-closed: # job 4
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
        - name: "Running on pull request closed" # step 1
          run: echo "Running on pull request closed"

    on-workflow-dispatch: # job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
        - name: "Running on workflow dispatch" # step 1
          run: echo "Running on workflow dispatch"

         